name: Release

on:
  # workflow_run: # Only runs on main branch
  #     workflows: ["Check Rust"]
  #     types:
  #       - completed
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  release:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build project
      run: cargo build --release
    
    # - name: Verify Version
    #   run: |
    #     TAG_VERSION=${GITHUB_REF#refs/tags/v}
    #     CARGO_VERSION=$(grep '^version =' Cargo.toml | sed -E 's/version = "([^"]+)"/\1/')
    #     if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
    #       echo "Version mismatch: tag is $TAG_VERSION but Cargo.toml is $CARGO_VERSION"
    #       exit 1  # Exits with a non-zero status to fail the workflow
    #     fi
    #   shell: bash
    
    - name: Create GitHub release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes

    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        echo "Publishing to crates.io"  